### ISSUE TITLE
Localized strack traces cannot be parsed by HockeyApp services (.Net)

### ISSUE THREAD

**Issue by tseifried** [bitstadium/HockeySDK-Windows#141] opened 2018-04-17 14:29 UTC
The call stack sent to the HockeyApp services is localized in .net, causing the HockeyApp service to not being able to parse it correctly.

For example this crash in Japanese:
```
Package: TestApp
Version: 3.4.6.0
OS: Windows
Windows: 6.3.10586.0
Date: 2018-02-12T04:39:04.6649385Z

System.ArgumentOutOfRangeException: 指定された引数は、有効な値の範囲内にありませんパラメーター名:index
   場所 System.Windows.Media.VisualCollection.get_Item(Int32 index)
   場所 System.Windows.Documents.AdornerLayer.GetVisualChild(Int32 index)
   場所 System.Windows.Media.Visual.InternalGet2DOr3DVisualChild(Int32 index)
   場所 System.Windows.UIElement.InvalidateForceInheritPropertyOnChildren(Visual v, DependencyProperty property)
```
Results in this output on the service:
![image](https://user-images.githubusercontent.com/18345723/38875841-9535ce48-425b-11e8-8b6b-d1c587def714.png)

This is rather problematic, since this will also cause the integration to bug trackers not be triggered.

According to https://stackoverflow.com/questions/209133/exception-messages-in-english it should be possible to change the CurrentCulture of the thread to InvariantCulture to receive the stack trace in English, however I have not tested this so far.

I am able to reproduce this in the .Net (WPF) module, but this should apply to at least all .Net applications.

**Comment by MatkovIvan** [comment] 2018-04-18 08:34
Hi @tseifried 

Thanks for getting in touch.
This is duplicate of #108
It's more tricky because localization can be performed when an exception is created. Also, after an unhandled crash, we cannot just create a new thread since the whole application will close immediately. So, this approach doesn't look as good solution for that. It's better to improve parsing on the server side (known issue).

Best,
Ivan

**Closed** 2020-02-19 14:11 UTC
Labels: bug
