### ISSUE TITLE
CheckForUpdatesAsync throws exception when debugger is attached

### ISSUE THREAD

**Issue by jgcoded** [bitstadium/HockeySDK-Windows#136] opened 2018-02-19 00:29 UTC
When debugging my WPF app, I get this exception when I make the call to `HockeyClient.Current.CheckForUpdatesAsync`: `System.NullReferenceException: 'Object reference not set to an instance of an object.`

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.HockeyApp.Kit
  StackTrace:
   at Microsoft.HockeyApp.HockeyPlatformHelperWPF.get_AppVersion()
```

This doesn't affect my app when running outside of the debugger. I'm using HockeySDK.WPF v4.1.6

**Comment by TroubleMakerBen** [comment] 2018-02-20 18:37
Hi,
I've added a task for this to our backlog. Thanks for reporting this.

Best,
Benjamin

**Comment by bmourat** [comment] 2018-03-12 12:36
Hi @jgcoded 

I could not reproduce this, could you provide more info on your project setup and full stack trace of this exception? Is it just pure WPF app or some unmanaged code is involved? I think I found a possible reason for this, but I want to be sure. As it seems a call to ```Assembly.GetEntryAssembly()``` could return a null value in some cases and thus result in null pointer exception.

Thanks,
Murat

**Comment by jgcoded** [comment] 2018-03-13 14:59
Hi @bmourat, I have left more detail on #135. It's a WPF app with managed code and I run it as a uwp app using the Desktop Bridge tool. I can verify the return value of the GetEntryAssembly function in my project if needed.

**Comment by YoungjaeKim** [comment] 2018-03-19 10:25
I got exactly same problem but not Desktop-bridge tool. Mine is pure WPF .net 4.6.1 program.
I'm not using `StartupUri` or `Properties>Startup object`
Instead, I'm invoking `MainWindow` as below.

```CSharp
        protected override async void OnStartup(StartupEventArgs e)
        {
            new MainWindow().Show(); // <- here
            base.OnStartup(e);

            HockeyClient.Current.Configure("KEY");

            await HockeyClient.Current.SendCrashesAsync();
            await HockeyClient.Current.CheckForUpdatesAsync(true, () =>
            {
                if (Application.Current.MainWindow != null)
                {
                    Application.Current.MainWindow.Close();
                }
                return true;
            });
        }
```

**Comment by bmourat** [comment] 2018-03-19 11:24
@YoungjaeKim 
Does this affect your app running or you are just seeing this line in the debug output?

**Comment by YoungjaeKim** [comment] 2018-03-19 14:07
@bmourat app runs fine. only exception is given at debug output.

**Comment by bmourat** [comment] 2018-03-20 07:49
@YoungjaeKim this is intended behavior, and you can safely ignore this, you can see the the chunk of code responsible for this [here](https://github.com/bitstadium/HockeySDK-Windows/blob/develop/Src/Kit.WPF/HockeyPlatformHelperWPF.cs#L253)

**Comment by YoungjaeKim** [comment] 2018-04-03 06:17
thanks. let me close this issue.

**Comment by YoungjaeKim** [comment] 2018-04-03 06:17
@bmourat got it. thanks for the reply.

**Closed** 2018-04-03 16:33 UTC
