### ISSUE TITLE
UWP (win10) - prelaunch of app causes session start/end.

### ISSUE THREAD

**Issue by quincycs** [bitstadium/HockeySDK-Windows#74] opened 2016-09-29 13:26 UTC
On a UWP (win10) app, if the OS prelaunches it, then it logs session start for this user.  This is an incorrect metric b/c prelaunch is not a user initiated action, therefore can create incorrect user metrics.

https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/handle-app-prelaunch
https://blogs.windows.com/buildingapps/2016/04/28/the-lifecycle-of-a-uwp-app/#1iTVpyhMceWoDUxy.97

**Comment by quincycs** [comment] 2016-12-08 16:29
The workaround fix is to change the initialization of HA SDK until you know the app has been launched by a real user.

OnActivated()
OnShareTargetActivated()
OnLaunched()  {  if (e.PrelaunchActivated) return; }

^During the above method calls I think thats when you know the app has been launched by a real user.  You should construct HA in each of these calls b/c there are scenarios where only one of them is called.  E.g. OnLaunched() isn't always called.

**Comment by achocron** [comment] 2017-01-25 22:10
Unfortunately there is no fix within the SDK for this issue, but an alternative workaround can be found in the UWP demo application at https://github.com/bitstadium/HockeySDK-WindowsDemo

**Comment by quincycs** [comment] 2017-01-25 22:14
@achocron the downside of this workaround is that if the app crashes before HA is initialized then the crash will never be logged

**Comment by quincycs** [comment] 2017-02-07 18:29
i updated the above issue with what I do if the app crashes before HA is initialized

**Comment by elamalani** [comment] 2018-03-14 21:58
@quincycs This is the expected behavior and is by design where you cannot get app crashes before HA is initialized. I'm closing this issue for now but please feel free to ask us any other questions. Thanks!

**Closed by elamalani** 2018-03-14 21:58 UTC
